---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
  # vars:
  #   ipaserver_external_ca: yes
  #   ipaserver_copy_csr_to_controller: yes
    
  roles:
  - role: freeipa.ansible_freeipa.ipaserver
    state: present
